Upgrade dependencies to match quality checklist
TwilioDevEd/account-security-quickstart-rails pull request #47
Opened 2020-03-31 21:23 UTC by po5i

Resolves #46

2020-06-15 23:38 UTC, mmena1 requested changes
Nice work Angie! I see a lot of improvements over the old code. I left some minor comments about grammar and code cleanup. I do have a concern though:

Rails 6 brought some [big changes](https://edgeguides.rubyonrails.org/6_0_release_notes.html#railties-notable-changes) over its predecessor, one of them is the inclusion of `webpack` to serve front-end assets which is now the default JavaScript compiler. In order to get the new Rails 6 structure we need to add a NodeJS engine to provide the webpack feature which will be consumed through [Webpacker](https://github.com/rails/webpacker). The easiest way to add this is to create a new project from scratch (or use the [sample template](https://github.com/TwilioDevEd/sample-template-rails)) then copy all the content to the new project and move the contents from the public directory to the new assets path.

_Other minor stuff:_

- This [image](https://github.com/TwilioDevEd/account-security-quickstart-rails/blob/783a175c6bda973be95579b7cee807852e7d7430/api_key.png) should be removed.

2020-06-15 23:38 UTC, mmena1 commented on .github/workflows/ruby.yml
> +    runs-on: ubuntu-latest
This should also be able to run on mac and linux. Please refer to this [example](https://github.com/TwilioDevEd/sample-template-rails/blob/master/.github/workflows/rails.yml)

2020-06-15 23:38 UTC, mmena1 commented on .github/workflows/ruby.yml
> +        ruby-version: 2.6.x
The newest ruby version is `2.7.1` and we should upgrade to that version. On this [ruby template](https://github.com/TwilioDevEd/sample-template-rails) we use version `2.6.x` because at that time, `2.7.0` had some issues with the Windows CI

2020-06-15 23:38 UTC, mmena1 commented on Makefile
> +	bundle exec rails server --binding 0.0.0.0
As a good practice, all Makefiles should include a `.PHONY` [entry](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html).

**TL;DR**
By default, the `make` command targets files, so `make install` is actually looking for a file named `install` but since it doesn't exist it will execute the rule `install` on the Makefile. By adding `.PHONY: install`, we are telling the `make` command that `install` is not a file and should always run as the name of the recipe to be executed, even if there is a file named `install`. So, as a rule of thumb, all rules defined on the Makefile should be declared as `.PHONY` targets to avoid any potential collisions with similar named files.

2020-06-15 23:38 UTC, mmena1 commented on README.md
This should be removed. Talk to Dominik to know if this isn't needed anymore

2020-06-15 23:38 UTC, mmena1 commented on app/controllers/api/verify_controller.rb
> +    verification
We don't need this line. Ruby always returns the evaluated expression on the last line of a function unless there is an explicit `return` statement after it.

2020-06-15 23:38 UTC, mmena1 commented on app/controllers/api/verify_controller.rb
> +    verification_check
Here, same as above

2020-06-15 23:38 UTC, mmena1 commented on spec/controllers/twofa_controller_spec.rb
> +    context 'when a user not exists ' do
```suggestion
    context 'when a user does not exist ' do
```

2020-06-15 23:38 UTC, mmena1 commented on spec/controllers/twofa_controller_spec.rb
> +    context 'when a user not exists ' do
```suggestion
    context 'when a user does not exist ' do
```

2020-06-15 23:38 UTC, mmena1 commented on spec/controllers/twofa_controller_spec.rb
> +    context 'when a user not exists ' do
```suggestion
    context 'when a user does not exist ' do
```

2020-06-15 23:38 UTC, mmena1 commented on spec/controllers/twofa_controller_spec.rb
> +    context 'when a user not exists ' do
```suggestion
    context 'when a user does not exist ' do
```

2020-06-17 16:12 UTC, rojasTob commented
> Nice work Angie! I see a lot of improvements over the old code. I left some minor comments about grammar and code cleanup. I do have a concern though:
> 
> Rails 6 brought some [big changes](https://edgeguides.rubyonrails.org/6_0_release_notes.html#railties-notable-changes) over its predecessor, one of them is the inclusion of `webpack` to serve front-end assets which is now the default JavaScript compiler. In order to get the new Rails 6 structure we need to add a NodeJS engine to provide the webpack feature which will be consumed through [Webpacker](https://github.com/rails/webpacker). The easiest way to add this is to create a new project from scratch (or use the [sample template](https://github.com/TwilioDevEd/sample-template-rails)) then copy all the content to the new project and move the contents from the public directory to the new assets path.
> 
> _Other minor stuff:_
> 
> * This [image](https://github.com/TwilioDevEd/account-security-quickstart-rails/blob/783a175c6bda973be95579b7cee807852e7d7430/api_key.png) should be removed.

Hey @mrcrow85 , about your comment of the NodeJS engine, thanks for pointing this out. I'm going to talk about this with Dominik and check if it is possible to do this in this phase.

2020-06-17 16:50 UTC, mmena1 reviewed
Looks good 👍

2020-06-17 16:51 UTC, mmena1 approved these changes

2020-06-17 17:10 UTC, merged